import { formatTime } from "@/lib/utils";
import { symptomLabel } from "@/lib/types/health";
import type { StudentHealthState } from "@/lib/types/health";

export function buildAppointmentSummary(state: StudentHealthState): string {
  const reasons =
    state.activeSymptoms.length > 0
      ? state.activeSymptoms.map((s) => symptomLabel(s.name, s.customLabel)).join(" and ")
      : "Not specified in the app";

  const timeline: { at: string; text: string }[] = [];
  for (const symptom of state.activeSymptoms) {
    timeline.push(
      { at: symptom.startedAt, text: `${formatTime(symptom.startedAt)} — ${symptomLabel(symptom.name, symptom.customLabel)} began (severity ${symptom.severity === null ? "not provided" : `${symptom.severity}/5`}, ${symptom.trend}). ${symptom.notes ?? ""}` },
    );
  }
  for (const entry of state.symptomHistory) {
    if (!state.activeSymptoms.some((symptom) => symptom.id === entry.symptomId)) {
      timeline.push({ at: entry.at, text: `${formatTime(entry.at)} — historical entry: ${symptomLabel(entry.name)} (severity ${entry.severity ?? "not provided"}, ${entry.trend})` });
    }
  }
  for (const reading of state.temperatureHistory) {
    timeline.push({ at: reading.at, text: `${formatTime(reading.at)} — temperature ${reading.fahrenheit.toFixed(1)}°F` });
  }
  timeline.sort((a, b) => Date.parse(a.at) - Date.parse(b.at));

  const associated = state.activeSymptoms
    .map((s) => symptomLabel(s.name, s.customLabel))
    .join(", ");

  const negatives = [
    state.importantNegatives ? `Student reports: ${state.importantNegatives}` : "No important negatives explicitly recorded.",
    "This summary only includes what was entered in the prototype.",
    "Absence of a symptom here does not mean it was clinically ruled out.",
  ];

  const meds =
    state.medications.length === 0
      ? "None logged"
      : state.medications
          .map((med) => {
            const ingredients =
              med.activeIngredients.length > 0
                ? ` (ingredients noted: ${med.activeIngredients.join(", ")})`
                : "";
            return `${med.name}${med.dose ? ` ${med.dose}` : ""} — ${formatTime(med.takenAt)}${ingredients}${med.notes ? ` — ${med.notes}` : ""}`;
          })
          .join("\n");

  const questions = [
    "When is it reasonable to return to class, lab, or athletic activity?",
    "Are any tests appropriate based on these symptoms?",
    "How should I use over-the-counter products without duplicating active ingredients?",
    "What warning signs mean I should seek care sooner?",
  ];

  return [
    "CLINICIAN-READY SUMMARY (student-prepared notes — not a diagnosis)",
    "",
    "Reason for visit:",
    reasons,
    "",
    "Symptom timeline:",
    timeline.length > 0 ? timeline.map((item) => item.text).join("\n") : "Not enough timeline data logged yet.",
    "",
    "Relevant measurements:",
    state.temperatureHistory.length > 0
      ? state.temperatureHistory
          .map((t) => `${formatTime(t.at)} — ${t.fahrenheit.toFixed(1)}°F`)
          .join("\n")
      : "No temperatures logged.",
    "",
    "Medications taken:",
    meds,
    "",
    "Associated symptoms:",
    associated || "None logged",
    "",
    "Important negatives:",
    negatives.map((line) => `- ${line}`).join("\n"),
    "",
    "Questions the student may want to ask:",
    questions.map((q) => `- ${q}`).join("\n"),
    "",
    "Safety note: This summary was generated by a student prototype and may be incomplete. It does not replace a clinical history.",
  ].join("\n");
}
